apiVersion: v1
kind: Service
metadata:
  name: webtop-service
spec:
  selector:
    app: webtop
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtop-deployment
  labels:
    app: webtop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webtop
  template:
    metadata:
      labels:
        app: webtop
    spec:
      containers:
      - name: webtop
        image: "$DOCKER_IMAGE"
        ports:
        - name: http
          containerPort: 3000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 2000m
        envFrom:
        - secretRef:
            name: webtop-secret
