apiVersion: v1
kind: Service
metadata:
  name: bzfs-service
spec:
  type: NodePort
  selector:
    app: bzfs
  ports:
  - name: bzfs-tcp
    protocol: TCP
    port: 5154
    targetPort: 5154
    nodePort: 32154
  - name: bzfs-udp
    protocol: UDP
    port: 5154
    targetPort: 5154
    nodePort: 32154
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bzfs-deployment
  labels:
    app: bzfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bzfs
  template:
    metadata:
      labels:
        app: bzfs
    spec:
      containers:
      - name: bzfs
        image: "$DOCKER_IMAGE"
        ports:
        - containerPort: 5154
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 2000m
